// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantEncyclopedia.Infrastructure.Persistence;

#nullable disable

namespace PlantEncyclopedia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlantEncyclopediaDbContext))]
    partial class PlantEncyclopediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_slug");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CultivarName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cultivar_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("PlantGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_group_id");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scientific_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaxonomyId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxonomy_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_plants");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_plants_display_name");

                    b.HasIndex("PlantGroupId")
                        .HasDatabaseName("ix_plants_plant_group_id");

                    b.HasIndex("ScientificName")
                        .HasDatabaseName("ix_plants_scientific_name");

                    b.HasIndex("TaxonomyId")
                        .HasDatabaseName("ix_plants_taxonomy_id");

                    b.ToTable("plants", null, t =>
                        {
                            t.HasCheckConstraint("ck_plants_published_requires_group", "status <> 'Published' OR plant_group_id IS NOT NULL");

                            t.HasCheckConstraint("ck_plants_status", "status IN ('Draft', 'Validated', 'Published', 'NeedsReview', 'Archived')");
                        });
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantCare", b =>
                {
                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LightDetails")
                        .HasColumnType("text")
                        .HasColumnName("light_details");

                    b.Property<string>("LightSummary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("light_summary");

                    b.Property<string>("SoilDetails")
                        .HasColumnType("text")
                        .HasColumnName("soil_details");

                    b.Property<string>("SoilSummary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("soil_summary");

                    b.Property<string>("TemperatureDetails")
                        .HasColumnType("text")
                        .HasColumnName("temperature_details");

                    b.Property<decimal?>("TemperatureMaxC")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_max_c");

                    b.Property<decimal?>("TemperatureMinC")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_min_c");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verification_status");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("WaterDetails")
                        .HasColumnType("text")
                        .HasColumnName("water_details");

                    b.Property<string>("WaterSummary")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("water_summary");

                    b.HasKey("PlantId")
                        .HasName("pk_plant_care");

                    b.ToTable("plant_care", null, t =>
                        {
                            t.HasCheckConstraint("ck_plant_care_temp_max_range", "temperature_max_c IS NULL OR temperature_max_c BETWEEN -60 AND 60");

                            t.HasCheckConstraint("ck_plant_care_temp_min_range", "temperature_min_c IS NULL OR temperature_min_c BETWEEN -60 AND 60");

                            t.HasCheckConstraint("ck_plant_care_temp_order", "temperature_min_c IS NULL OR temperature_max_c IS NULL OR temperature_min_c <= temperature_max_c");

                            t.HasCheckConstraint("ck_plant_care_verification_status", "verification_status IN ('Unverified', 'Verified')");

                            t.HasCheckConstraint("ck_plant_care_verified_at", "verification_status <> 'Verified' OR verified_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_plant_groups");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_plant_groups_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_plant_groups_slug");

                    b.ToTable("plant_groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_plant_groups_slug", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alt_text");

                    b.Property<string>("Attribution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attribution");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("LargeUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("large_url");

                    b.Property<string>("License")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("license");

                    b.Property<string>("MediumUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("medium_url");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<DateTimeOffset?>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_plant_images");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_plant_images_plant_id");

                    b.ToTable("plant_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_plant_images_height", "height IS NULL OR height > 0");

                            t.HasCheckConstraint("ck_plant_images_width", "width IS NULL OR width > 0");
                        });
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name_type");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.HasKey("Id")
                        .HasName("pk_plant_names");

                    b.HasIndex("PlantId", "NameType", "Name", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ux_plant_names_plant_type_name_language");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("PlantId", "NameType", "Name", "LanguageCode"), false);

                    b.ToTable("plant_names", null, t =>
                        {
                            t.HasCheckConstraint("ck_plant_names_common_language", "name_type <> 'Common' OR language_code IS NOT NULL");

                            t.HasCheckConstraint("ck_plant_names_language_code_shape", "language_code IS NULL OR language_code ~ '^[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*$'");

                            t.HasCheckConstraint("ck_plant_names_name_type", "name_type IN ('Common', 'Synonym')");
                        });
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_plant_sources");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_plant_sources_plant_id");

                    b.HasIndex("PlantId", "Provider", "ExternalId", "SourceType")
                        .IsUnique()
                        .HasDatabaseName("ux_plant_sources_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("PlantId", "Provider", "SourceUrl", "SourceType")
                        .IsUnique()
                        .HasDatabaseName("ux_plant_sources_source_url")
                        .HasFilter("external_id IS NULL");

                    b.ToTable("plant_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_plant_sources_identifier", "external_id IS NOT NULL OR source_url IS NOT NULL");

                            t.HasCheckConstraint("ck_plant_sources_source_type", "source_type IN ('Taxonomy', 'Description', 'Care', 'Image', 'Blooming', 'Health', 'About')");
                        });
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.Taxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Class")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family");

                    b.Property<string>("Genus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genus");

                    b.Property<string>("Kingdom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kingdom");

                    b.Property<string>("Phylum")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phylum");

                    b.Property<string>("Species")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("species");

                    b.Property<string>("Subspecies")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subspecies");

                    b.Property<string>("TaxonOrder")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("taxon_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Variety")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variety");

                    b.HasKey("Id")
                        .HasName("pk_taxonomies");

                    b.ToTable("taxonomies", (string)null);
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.Plant", b =>
                {
                    b.HasOne("PlantEncyclopedia.Domain.Plants.PlantGroup", "PlantGroup")
                        .WithMany("Plants")
                        .HasForeignKey("PlantGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plants_plant_groups_plant_group_id");

                    b.HasOne("PlantEncyclopedia.Domain.Plants.Taxonomy", "Taxonomy")
                        .WithMany("Plants")
                        .HasForeignKey("TaxonomyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plants_taxonomies_taxonomy_id");

                    b.Navigation("PlantGroup");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantCare", b =>
                {
                    b.HasOne("PlantEncyclopedia.Domain.Plants.Plant", "Plant")
                        .WithOne("Care")
                        .HasForeignKey("PlantEncyclopedia.Domain.Plants.PlantCare", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plant_care_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantGroup", b =>
                {
                    b.HasOne("PlantEncyclopedia.Domain.Plants.Category", "Category")
                        .WithMany("PlantGroups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plant_groups_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantImage", b =>
                {
                    b.HasOne("PlantEncyclopedia.Domain.Plants.Plant", "Plant")
                        .WithMany("Images")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plant_images_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantName", b =>
                {
                    b.HasOne("PlantEncyclopedia.Domain.Plants.Plant", "Plant")
                        .WithMany("Names")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plant_names_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantSource", b =>
                {
                    b.HasOne("PlantEncyclopedia.Domain.Plants.Plant", "Plant")
                        .WithMany("Sources")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plant_sources_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.Category", b =>
                {
                    b.Navigation("PlantGroups");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.Plant", b =>
                {
                    b.Navigation("Care");

                    b.Navigation("Images");

                    b.Navigation("Names");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.PlantGroup", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantEncyclopedia.Domain.Plants.Taxonomy", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
